#!/usr/bin/env bash
# One-time: make Isaac ROS Dev containers include SAM / examples / cv_bridge / numpy<2
# so you do NOT re-apt every time the container is recreated.
set -euo pipefail

WS="${ISAAC_ROS_WS:-$HOME/generalized_picking_ws}"
DOCKER_DIR="${WS}/docker"
CONFIG="${HOME}/.isaac_ros_common-config"

if [[ ! -f "${DOCKER_DIR}/Dockerfile.perception" ]]; then
  echo "Missing ${DOCKER_DIR}/Dockerfile.perception"
  exit 1
fi

cat > "${CONFIG}" <<EOF
# Generated by enable_persistent_isaac_ros.sh — generalized_picking_ws
# Builds: x86_64.ros2_humble.perception (base humble image + perception packages)
CONFIG_IMAGE_KEY="ros2_humble.perception"
CONFIG_DOCKER_SEARCH_DIRS=("${DOCKER_DIR}")
EOF

echo "Wrote ${CONFIG}"
echo ""
echo "Next (ONE rebuild — can take a while, but only once):"
echo "  1) Exit any running Isaac ROS container (all admin shells)."
echo "  2) On the host:"
echo "       source ~/.bashrc"
echo "       cd \${ISAAC_ROS_WS}/src/isaac_ros_common"
echo "       ./scripts/run_dev.sh"
echo ""
echo "You should see image key: x86_64.ros2_humble.perception"
echo "After that, ros-humble-isaac-ros-segment-anything / examples / cv_bridge should already be installed."
echo ""
echo "Verify inside container:"
echo "  source /opt/ros/humble/setup.bash"
echo "  ros2 pkg prefix isaac_ros_segment_anything"
echo "  ros2 pkg prefix isaac_ros_examples"
echo "  python3 -c \"import numpy; import cv2; print(numpy.__version__)\""
